name: Windows Build

on:
  push:
    branches: [ "feature/deoldify-integration" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja -y

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          cache: true

      - name: Clean and Get dependencies
        run: |
          flutter clean
          Remove-Item -Force pubspec.lock -ErrorAction SilentlyContinue
          flutter pub get

      - name: Build Runner
        run: |
          if (Select-String -Path pubspec.yaml -Pattern "build_runner" -Quiet) {
            dart run build_runner build --delete-conflicting-outputs
          }

      - name: Build Windows
        run: flutter build windows --release -t lib/src/main.dart
        env:
          CMAKE_GENERATOR: Ninja

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath jhentai-windows-release.zip

      - name: Upload Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: jhentai-windows-release
          path: jhentai-windows-release.zip
